id = "puzzle"
name = "Puzzle"
description = "Puzzle single-file component language support"
version = "0.1.0"
schema_version = 1
authors = ["Magic Spells"]
repository = "https://github.com/magic-spells/puzzle-zed"

[grammars.puzzle]
repository = "file:///Users/coryschulz/Code/@magic-spells/puzzle-zed"
commit = "26b149ef32e0e4a7d6bcce9b6f0c6325b06db392"
