id = "puzzle"
name = "Puzzle"
description = "Puzzle single-file component language support"
version = "0.4.0"
schema_version = 1
authors = ["Magic Spells"]
repository = "https://github.com/magic-spells/puzzle-zed"

[grammars.puzzle]
repository = "file:///Users/coryschulz/Code/@magic-spells/puzzle/editors/puzzle-zed"
commit = "3052bb400b667ab8beae355333858390296a9793"
