id = "puzzle"
name = "Puzzle"
description = "Puzzle single-file component language support"
version = "0.4.0"
schema_version = 1
authors = ["Magic Spells"]
repository = "https://github.com/magic-spells/puzzle-zed"

[grammars.puzzle]
repository = "file:///Users/coryschulz/Code/@magic-spells/puzzle/editors/puzzle-zed"
commit = "63ba0a329122f573ace24b7cf791d91d380d58c5"
