name = "Puzzle"
grammar = "puzzle"
path_suffixes = ["pzl"]
tab_size = 2
hard_tabs = false
block_comment = { start = "<!--", prefix = "", end = "-->", tab_size = 0 }
autoclose_before = ":\"'}]>"
wrap_characters = { start_prefix = "<", start_suffix = ">", end_prefix = "</", end_suffix = ">" }
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<!--", end = " -->", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "`", end = "`", close = true, newline = false, not_in = ["string", "comment"] },
]
scope_opt_in_language_servers = ["tailwindcss-language-server"]

[jsx_tag_auto_close]
open_tag_node_name = "start_tag"
close_tag_node_name = "end_tag"
jsx_element_node_name = "element"
tag_name_node_name = "tag_name"

[overrides.string]
completion_query_characters = ["-"]
opt_into_language_servers = ["tailwindcss-language-server"]
